# Generated by Django 5.2.4 on 2025-07-26 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
                ('sub_section', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('SME', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(max_length=50)),
                ('completion', models.CharField(default='0%', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='online_help.document')),
            ],
        ),
        migrations.CreateModel(
            name='MajorDocu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.CharField(max_length=255)),
                ('SME', models.CharField(max_length=255)),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_docs', to='online_help.writers')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_docs', to='online_help.writers')),
            ],
        ),
        migrations.CreateModel(
            name='TaskWriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_help.task')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_help.writers')),
            ],
            options={
                'unique_together': {('task', 'writer')},
            },
        ),
    ]
